export const QUERY_KEYS = {
    AUTH_USER: "AUTH_USER",
    COMPANIES: "COMPANIES",
    MY_COMPANY: "MY_COMPANY",
    COMPANY: "COMPANY",
    JOBS: "JOBS",
    JOB: "JOB",
    APPLICATIONS: "APPLICATIONS",
    RECRUITER_APPLICATIONS: "RECRUITER_APPLICATIONS",
    JOB_APPLICATIONS: "JOB_APPLICATIONS",
    SAVED_JOBS: "SAVED_JOBS",
    DASHBOARD_STATS: "DASHBOARD_STATS",
    NOTIFICATIONS: "NOTIFICATIONS",
};
